//researchers
export const REQUEST_RESEARCHERS = "REQUEST_RESEARCHERS"
export const RECEIVE_RESEARCHERS = "RECEIVE_RESEARCHERS"
export const INVALIDATE_RESEARCHERS = "INVALIDATE_RESEARCHERS"
export const SELECT_RESEARCHER = "SELECT_RESEARCHER"
export const REGISTER_RESEARCHER = "REGISTER_RESEARCHER"
export const CHANGE_ROLE = "CHANGE_ROLE"
export const EDIT_PROFILE = "EDIT_PROFILE"

//Auth
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS"
export const SIGNOUT_FAIL = "SIGNOUT_FAIL"

//form
export const VALIDATE = "VALIDATE"
export const FORM_CHANGE = "FORM_CHANGE"
export const CLEAR_FORM = "CLEAR_FORM"
export const INITIALIZE_PROFILE = "INITIALIZE_PROFILE"
export const SET = "SET"
export const EDIT = "EDIT"
export const SELECT_DROPDOWN_ITEM = "SELECT_DROPDOWN_ITEM"
export const ADD_AGE_CONSTRAINT = "ADD_AGE_CONSTRAINT"
export const ADD_OTHER_CONSTRAINT = "ADD_OTHER_CONSTRAINT"
export const UNSELECT_CONSTRAINT = "UNSELECT_CONSTRAINT"
export const CLEAR_CONSTRAINT = "CLEAR_CONSTRAINT"
export const SET_MODAL = "SET_MODAL"
export const INITIALIZE_EDIT_STUDY = "INITIALIZE_EDIT_STUDY"
export const SET_CONSENT = "SET_CONSENT"

//studies
export const REQUEST_STUDIES = "REQUEST_STUDIES"
export const RECEIVE_STUDIES = "RECEIVE_STUDIES"
export const INVALIDATE_STUDIES = "INVALIDATE_STUDIES"
export const SELECT_STUDY = "SELECT_STUDY"
export const CHANGE_STATUS = "CHANGE_STATUS"
export const ADD_RESEARCHER_TO_STUDY = "ADD_RESEARCHER_TO_STUDY"
export const REMOVE_RESEARCHER_FROM_STUDY = "REMOVE_RESEARCHER_FROM_STUDY"

//Health data
export const INVALIDATE_HEALTH_DATA = "INVALIDATE_HEALTH_DATA"
export const REQUEST_HEALTH_DATA = "REQUEST_HEALTH_DATA"
export const RECEIVE_HEALTH_DATA = "RECEIVE_HEALTH_DATA"