//researchers
export const REQUEST_RESEARCHERS = "REQUEST_RESEARCHERS"
export const RECEIVE_RESEARCHERS = "RECEIVE_RESEARCHERS"
export const INVALIDATE_RESEARCHERS = "INVALIDATE_RESEARCHERS"
export const SELECT_RESEARCHER = "SELECT_RESEARCHER"
export const ADD_RESEARCHER_TO_STUDY = "ADD_RESEARCHER_TO_STUDY"
export const REGISTER_RESEARCHER = "REGISTER_RESEARCHER"
export const CHANGE_ROLE = "CHANGE_ROLE"
export const EDIT_PROFILE = "EDIT_PROFILE"

//Auth
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS"
export const SIGNOUT_FAIL = "SIGNOUT_FAIL"

//form
export const VALIDATE = "VALIDATE"
export const FORM_CHANGE = "FORM_CHANGE"
export const CLEAR_FORM = "CLEAR_FORM"
export const INITIALIZE_PROFILE = "INITIALIZE_PROFILE"
export const SET = "SET"
export const EDIT = "EDIT"
export const SELECT_DROPDOWN_ITEM = "SELECT_DROPDOWN_ITEM"
export const ADD_AGE_CONSTRAINT = "ADD_AGE_CONSTRAINT"
export const ADD_OTHER_CONSTRAINT = "ADD_OTHER_CONSTRAINT"
export const UNSELECT_CONSTRAINT = "UNSELECT_CONSTRAINT"
export const CLEAR_CONSTRAINT = "CLEAR_CONSTRAINT"

//studies
export const REQUEST_STUDIES = "REQUEST_STUDIES"
export const RECEIVE_STUDIES = "RECEIVE_STUDIES"
export const INVALIDATE_STUDIES = "INVALIDATE_STUDIES"
export const SELECT_STUDY = "SELECT_STUDY"